### ISSUE TITLE
Not showing processing Alert

### ISSUE THREAD

**Issue by ErAshu** [Lasithih/LIHAlert#3]
Hey, i am using below this code just after init and Processing alert is not showing. If i paste this in button click event, working fine. I have to use this in viewDidLoad. How can i achieve this?

`self.processingAlert?.show(nil, hidden: nil)`

**Comment by Lasithih** [comment]
Please submit your entire code block

**Comment by ErAshu** [comment]
```
override func viewDidLoad() {
        super.viewDidLoad()
        
        self.processingAlert = LIHAlertManager.getProcessingAlert(message: "Fetching data...")
        self.processingAlert?.touchBackgroundToDismiss = true
        self.processingAlert?.dimsBackground = true
        self.processingAlert?.initAlert(self.view)

        self.processingAlert?.show(nil, hidden: nil)
}
```

**Comment by Lasithih** [comment]
Do not show the alert on viewDidLoad(). Try moving it to viewDidAppear()
