### ISSUE TITLE
Issue with iPhone x

### ISSUE THREAD

**Issue by aman198** [Lasithih/LIHAlert#4]
Can u suggest which alert property I can adjust so that will show proper in iPhone x

**Comment by Lasithih** [comment]
Could you post a screenshot showing how it displays now?

**Comment by aman198** [comment]
This is my Code
if UIDevice().userInterfaceIdiom == .phone {
            switch UIScreen.main.nativeBounds.height {
            case 2436:
                print("iPhone X")
                alertHeight = 100
                alertTop = 13
            default:
                print("default ")
                alertHeight = 70
                alertTop = 0
            }
        }
        

        let noDataLabel: UILabel     = UILabel(frame: CGRect(x: 0, y: 0, width: self.view.bounds.width, height: alertHeight))
        noDataLabel.text          = AlertMessageEventsSeatingAndInvites.alertPrompt.rawValue
        noDataLabel.textColor     = UIColor.white
        noDataLabel.numberOfLines = 0
        noDataLabel.textAlignment = .left
        noDataLabel.padding = UIEdgeInsets(top:alertTop, left:5, bottom: 0, right: 5)
        

        self.customViewAlert = LIHAlertManager.getCustomViewAlert(customView: noDataLabel)
        self.customViewAlert?.alertHeight = alertHeight

       
        
        customViewAlert?.alertColor = alertBackgroundColor
        self.customViewAlert?.hasNavigationBar = true
        self.customViewAlert?.autoCloseTimeInterval = 3.0
        self.customViewAlert?.touchBackgroundToDismiss = true
        self.customViewAlert?.initAlert(self.view)


In this I am managing alert

**Comment by Lasithih** [comment]
Should be fixed by now
